name = "C"
grammar = "c"
path_suffixes = ["c"]
line_comments = ["// "]
decrease_indent_patterns = [
  { pattern = "^\\s*\\{.*\\}?\\s*$", valid_after = ["if", "for", "while", "do", "switch", "else"] },
  { pattern = "^\\s*else\\b", valid_after = ["if"] }
]
debuggers = ["CodeLLDB", "GDB"]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
