name = "Go"
grammar = "go"
path_suffixes = ["go"]
modeline_aliases = ["golang"]
line_comments = ["// "]
first_line_pattern = '^//.*\bgo run\b'
debuggers = ["Delve"]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
auto_indent_strings = ["{", "[", "("]
auto_outdent_strings = ["}", "]", ")"]
