name = "JSON"
grammar = "json"
path_suffixes = ["json", "flake.lock", "geojson", "topojson", "prettierrc", "json.dist"]
line_comments = ["// "]
tab_size = 2
prettier_parser_name = "json"
debuggers = ["JavaScript"]
word_characters = ["#"]

[overrides.string]
completion_query_characters = [":", " ", "."]
