name = "Rust"
grammar = "rust"
path_suffixes = ["rs"]
modeline_aliases = ["rs", "rustic"]
line_comments = ["// ", "/// ", "//! "]
collapsed_placeholder = " /* ... */ "
debuggers = ["CodeLLDB", "GDB"]
block_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
