name = "Go"
grammar = "go"
path_suffixes = ["go"]
modeline_aliases = ["golang"]
line_comments = ["// "]
first_line_pattern = '^//.*\bgo run\b'
tab_size = 4
hard_tabs = true
debuggers = ["Delve"]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
